import { initializeApp } from "https://www.gstatic.com/firebasejs/12.17.0/firebase-app.js";
import { getAuth, signInWithEmailAndPassword, signOut, onAuthStateChanged, sendPasswordResetEmail, browserLocalPersistence, setPersistence } from "https://www.gstatic.com/firebasejs/12.17.0/firebase-auth.js";
import { getFirestore, collection, doc, addDoc, setDoc, getDoc, getDocs, deleteDoc, query, orderBy, serverTimestamp } from "https://www.gstatic.com/firebasejs/12.17.0/firebase-firestore.js";
import { initializeAppCheck, ReCaptchaEnterpriseProvider } from "https://www.gstatic.com/firebasejs/12.17.0/firebase-app-check.js";
import { firebaseConfig, appCheckSiteKey } from "./firebase-config.js";

const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const currency=new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"});
const compact=new Intl.NumberFormat("pt-BR",{notation:"compact",maximumFractionDigits:1});
const monthFmt=new Intl.DateTimeFormat("pt-BR",{month:"long",year:"numeric"});
const shortMonth=new Intl.DateTimeFormat("pt-BR",{month:"short"});
const categories={expense:["Moradia","Mercado","Restaurantes","Transporte","Veículo","Saúde","Pets","Assinaturas","Lazer","Compras","Impostos","Seguros","Educação","Viagens","Outros"],income:["Salário","Benefícios","Renda extra","Investimentos","Reembolso","Venda","Outros"]};
const palette=["#4fd1a3","#6ea8ff","#f7c65d","#ff8b84","#a78bfa","#55c7df","#f29f67","#93d66c"];
if(!firebaseConfig.projectId||firebaseConfig.projectId==="SUBSTITUA") throw new Error("Firebase não configurado");
const app=initializeApp(firebaseConfig);
if(appCheckSiteKey) initializeAppCheck(app,{provider:new ReCaptchaEnterpriseProvider(appCheckSiteKey),isTokenAutoRefreshEnabled:true});
const auth=getAuth(app),db=getFirestore(app); await setPersistence(auth,browserLocalPersistence);
let user=null,selectedMonth=new Date();selectedMonth.setDate(1);let txCache=[],positionsCache=[],settings={};
const userCol=n=>collection(db,"users",user.uid,n),userDoc=(n,id)=>doc(db,"users",user.uid,n,id);
const toast=msg=>{const t=$("#toast");t.textContent=msg;t.classList.add("show");setTimeout(()=>t.classList.remove("show"),2200)};
const ymd=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`;
const monthKey=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}`;
const esc=(s="")=>String(s).replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
const clamp=(v,min,max)=>Math.max(min,Math.min(max,v));
function iconFor(c){return({Moradia:"⌂",Mercado:"▣",Restaurantes:"◉",Transporte:"↗",Veículo:"◆",Saúde:"+",Pets:"♧",Assinaturas:"∞",Lazer:"☆",Compras:"▤",Impostos:"%",Seguros:"□",Educação:"▰",Viagens:"✈",Salário:"$",Benefícios:"◎",Investimentos:"↗"}[c]||"•")}
async function ensureUserRoot(){const r=doc(db,"users",user.uid),s=await getDoc(r);if(!s.exists())await setDoc(r,{createdAt:serverTimestamp(),email:user.email},{merge:true})}
async function loadAll(){await ensureUserRoot();await Promise.all([loadTransactions(),loadPositions(),loadSettings()]);renderAll()}
async function loadTransactions(){const s=await getDocs(query(userCol("transactions"),orderBy("date","desc")));txCache=s.docs.map(d=>({id:d.id,...d.data()}))}
async function loadPositions(){const s=await getDocs(query(userCol("positions"),orderBy("createdAt","desc")));positionsCache=s.docs.map(d=>({id:d.id,...d.data()}))}
async function loadSettings(){const s=await getDoc(userDoc("config","planning"));settings=s.exists()?s.data():{}}
function monthTransactions(d=selectedMonth){const k=monthKey(d);return txCache.filter(t=>String(t.date||"").startsWith(k))}
function calcMonth(d=selectedMonth){const txs=monthTransactions(d),income=txs.filter(t=>t.type==="income").reduce((s,t)=>s+Number(t.amount||0),0),expense=txs.filter(t=>t.type==="expense").reduce((s,t)=>s+Number(t.amount||0),0);return{txs,income,expense,balance:income-expense,savingRate:income?((income-expense)/income)*100:0}}
function calcPositions(){const assets=positionsCache.filter(p=>["asset","reserve"].includes(p.type)).reduce((s,p)=>s+Number(p.value||0),0),reserve=positionsCache.filter(p=>p.type==="reserve").reduce((s,p)=>s+Number(p.value||0),0),debts=positionsCache.filter(p=>p.type==="debt").reduce((s,p)=>s+Number(p.value||0),0);return{assets,reserve,debts,netWorth:assets-debts}}
function previousMonth(){const d=new Date(selectedMonth);d.setMonth(d.getMonth()-1);return calcMonth(d)}
function rollingAverageExpenses(){const map={};txCache.filter(t=>t.type==="expense").forEach(t=>{const k=String(t.date||"").slice(0,7);if(/^\d{4}-\d{2}$/.test(k))map[k]=(map[k]||0)+Number(t.amount||0)});const vals=Object.keys(map).sort().reverse().slice(0,6).map(k=>map[k]);return vals.length?vals.reduce((a,b)=>a+b,0)/vals.length:0}
function project(rate,years,start,monthly){const r=Math.pow(1+rate/100,1/12)-1,n=years*12;return start*Math.pow(1+r,n)+(r?monthly*(Math.pow(1+r,n)-1)/r:monthly*n)}
function freedomData(){const p=calcPositions(),monthly=Number(settings.financialFreedomMonthlyCost||0),target=monthly?monthly*12/.04:0,gap=target?Math.max(0,target-p.netWorth):0,percent=target?clamp(p.netWorth/target*100,0,100):0;return{target,gap,percent}}
function financeScore(){const m=calcMonth(),p=calcPositions(),avg=rollingAverageExpenses(),reserveMonths=avg?p.reserve/avg:0,targetMonths=Number(settings.reserveTargetMonths||6),debtRatio=p.assets?p.debts/p.assets:0;let score=0;score+=clamp(m.savingRate,0,30)/30*30;score+=clamp(reserveMonths/Math.max(1,targetMonths),0,1)*25;score+=(1-clamp(debtRatio,0,1))*25;score+=settings.monthlyContributionGoal?10:0;score+=settings.financialFreedomMonthlyCost?10:0;score=Math.round(clamp(score,0,100));let label="Construindo base";if(score>=85)label="Elite financeira";else if(score>=70)label="Estratégia forte";else if(score>=55)label="Em evolução";else if(score>=35)label="Base em formação";const level=Math.max(1,Math.floor(score/20)+1);return{score,label,level}}
function sixMonthSeries(){const out=[];for(let i=5;i>=0;i--){const d=new Date(selectedMonth);d.setMonth(d.getMonth()-i);const m=calcMonth(d);out.push({date:d,label:shortMonth.format(d).replace(".",""),income:m.income,expense:m.expense,balance:m.balance})}return out}
function renderAll(){renderDashboard();renderTransactions();renderPositions();renderPlanning()}
function renderDashboard(){const m=calcMonth(),prev=previousMonth(),p=calcPositions(),avg=rollingAverageExpenses(),rm=avg?p.reserve/avg:0,fd=freedomData(),sc=financeScore();$("#monthLabel").textContent=monthFmt.format(selectedMonth).replace(/^./,c=>c.toUpperCase());$("#netWorth").textContent=currency.format(p.netWorth);$("#patrimonyNetWorth").textContent=currency.format(p.netWorth);$("#freedomBadge").textContent=`${fd.percent.toFixed(1)}% da liberdade`;$("#financeScore").textContent=sc.score;$("#scoreLabel").textContent=sc.label;$("#scoreRing").style.setProperty("--p",`${sc.score}%`);$("#levelPill").textContent=`Nível ${sc.level}`;$("#scoreHint").textContent=sc.score>=70?"Sua estrutura está consistente. O foco agora é acelerar sem elevar o risco.":"O score sobe com reserva, poupança, redução de dívidas e metas definidas.";$("#monthBalance").textContent=currency.format(m.balance);const delta=prev.balance?((m.balance-prev.balance)/Math.abs(prev.balance))*100:null;$("#balanceTrend").textContent=delta===null?"Sem base comparativa":`${delta>=0?"▲":"▼"} ${Math.abs(delta).toFixed(0)}% vs. mês anterior`;$("#savingRate").textContent=`${m.savingRate.toFixed(1)}%`;$("#savingStatus").textContent=m.income?m.savingRate>=20?"Dentro de uma faixa forte":"Abaixo da meta de 20%":"Cadastre receitas do mês";$("#reserveMonths").textContent=`${rm.toFixed(1)} meses`;$("#reserveValue").textContent=currency.format(p.reserve);$("#debtValue").textContent=currency.format(p.debts);$("#debtRatio").textContent=p.assets?`${(p.debts/p.assets*100).toFixed(1)}% dos ativos`:"Sem ativos cadastrados";$("#freedomPercent").textContent=`${fd.percent.toFixed(1)}%`;$("#freedomRing").style.setProperty("--p",`${fd.percent}%`);$("#freedomTarget").textContent=fd.target?currency.format(fd.target):"Defina no planejamento";$("#freedomGap").textContent=fd.target?currency.format(fd.gap):"—";$("#expenseTotal").textContent=currency.format(m.expense);renderCashflowChart();renderExpenseDonut();renderInsights();renderMissions();renderProjectionChart();$("#recentTransactions").className="list";$("#recentTransactions").innerHTML=m.txs.slice(0,5).map(txRow).join("")||`<div class="empty-state">Nenhum lançamento neste mês.</div>`}
function renderCashflowChart(){const data=sixMonthSeries(),max=Math.max(1,...data.flatMap(d=>[d.income,d.expense])),W=680,H=210,pad=34,plotH=140,group=(W-pad*2)/data.length,bar=18;let bars="",labels="";data.forEach((d,i)=>{const x=pad+i*group+group/2,ih=d.income/max*plotH,eh=d.expense/max*plotH;bars+=`<rect x="${x-bar-2}" y="${H-42-ih}" width="${bar}" height="${ih}" rx="5" fill="#58d6a2"/><rect x="${x+2}" y="${H-42-eh}" width="${bar}" height="${eh}" rx="5" fill="#ff7d86"/>`;labels+=`<text x="${x}" y="${H-18}" text-anchor="middle" fill="#7f95ac" font-size="11">${esc(d.label)}</text>`});const grid=[0,.5,1].map(v=>`<line x1="${pad}" x2="${W-pad}" y1="${H-42-v*plotH}" y2="${H-42-v*plotH}" stroke="#1b3044" stroke-width="1"/>`).join("");$("#cashflowChart").innerHTML=`<svg viewBox="0 0 ${W} ${H}" preserveAspectRatio="none">${grid}${bars}${labels}</svg>`}
function renderExpenseDonut(){const m=calcMonth(),cats={};m.txs.filter(t=>t.type==="expense").forEach(t=>cats[t.category]=(cats[t.category]||0)+Number(t.amount||0));const rows=Object.entries(cats).sort((a,b)=>b[1]-a[1]);let acc=0,stops=[];rows.forEach(([c,v],i)=>{const start=acc,end=acc+(m.expense?v/m.expense*100:0);stops.push(`${palette[i%palette.length]} ${start}% ${end}%`);acc=end});$("#expenseDonut").style.setProperty("--donut",rows.length?`conic-gradient(${stops.join(",")})`:`conic-gradient(#1c2e40 0 100%)`);$("#categoryLegend").innerHTML=rows.slice(0,6).map(([c,v],i)=>`<div class="category-item"><i class="category-swatch" style="background:${palette[i%palette.length]}"></i><span>${esc(c)}</span><b>${m.expense?(v/m.expense*100).toFixed(0):0}%</b></div>`).join("")||`<div class="empty-state">Sem despesas</div>`}
function renderInsights(){const m=calcMonth(),prev=previousMonth(),p=calcPositions(),avg=rollingAverageExpenses(),rm=avg?p.reserve/avg:0,rows=[];if(m.expense&&prev.expense){const d=(m.expense-prev.expense)/prev.expense*100;rows.push({icon:d<=0?"↘":"↗",title:d<=0?"Despesas recuaram":"Despesas avançaram",text:`${Math.abs(d).toFixed(1)}% em relação ao mês anterior.`})}if(m.income)rows.push({icon:m.savingRate>=20?"✓":"!",title:`Poupança de ${m.savingRate.toFixed(1)}%`,text:m.savingRate>=20?"Você está preservando uma parcela relevante da renda.":"Abaixo de 20%, sua velocidade de acumulação fica mais limitada."});const cats={};m.txs.filter(t=>t.type==="expense").forEach(t=>cats[t.category]=(cats[t.category]||0)+Number(t.amount||0));const top=Object.entries(cats).sort((a,b)=>b[1]-a[1])[0];if(top)rows.push({icon:"◎",title:`${top[0]} lidera os gastos`,text:`Representa ${(top[1]/m.expense*100).toFixed(1)}% das despesas do mês.`});if(avg)rows.push({icon:rm>=Number(settings.reserveTargetMonths||6)?"◆":"△",title:`Reserva: ${rm.toFixed(1)} meses`,text:rm>=Number(settings.reserveTargetMonths||6)?"Cobertura compatível com sua meta atual.":"A reserva ainda está abaixo da meta definida no planejamento."});if(p.debts>0)rows.push({icon:"−",title:"Dívida registrada",text:`Saldo devedor de ${currency.format(p.debts)}. Priorize pelo CET e risco de liquidez.`});$("#insightsList").innerHTML=(rows.slice(0,5).map(x=>`<div class="insight"><div class="insight-icon">${x.icon}</div><div><strong>${x.title}</strong><p>${x.text}</p></div></div>`).join("")||`<div class="empty-state">Adicione movimentações e patrimônio para liberar insights.</div>`)}
function renderMissions(){const m=calcMonth(),p=calcPositions(),avg=rollingAverageExpenses(),rm=avg?p.reserve/avg:0,targetM=Number(settings.reserveTargetMonths||6),goal=Number(settings.monthlyContributionGoal||0),missions=[{name:"Guardar 20% da renda",done:m.income>0&&m.savingRate>=20,p:m.income?clamp(m.savingRate/20*100,0,100):0,desc:"Construa margem para investir todos os meses."},{name:`Reserva de ${targetM} meses`,done:rm>=targetM,p:clamp(rm/targetM*100,0,100),desc:"Proteja o plano contra imprevistos."},{name:"Definir meta de aporte",done:goal>0,p:goal>0?100:0,desc:"Transforme intenção em compromisso mensal."},{name:"Reduzir alavancagem",done:p.debts===0,p:p.assets?clamp((1-p.debts/p.assets)*100,0,100):(p.debts===0?100:0),desc:"Menos dívida aumenta resiliência e liberdade."}];const done=missions.filter(x=>x.done).length,xp=txCache.length*5+done*100;$("#xpPill").textContent=`${xp} XP`;$("#missionsList").innerHTML=missions.map((x,i)=>`<div class="mission ${x.done?"done":""}"><div class="mission-icon">${x.done?"✓":i+1}</div><div><strong>${x.name}</strong><p>${x.desc}</p><div class="mission-progress"><i style="width:${x.p}%"></i></div></div></div>`).join("")}
function renderProjectionChart(){const p=calcPositions(),monthly=Number(settings.monthlyContributionGoal||Math.max(0,calcMonth().balance)),rate=Number(settings.realReturn??5),pts=[0,5,10,20,30].map(y=>({years:y,value:y?project(rate,y,p.netWorth,monthly):p.netWorth})),max=Math.max(1,...pts.map(x=>x.value)),W=600,H=180,pad=28,coords=pts.map((pt,i)=>({x:pad+i*(W-pad*2)/(pts.length-1),y:H-28-(pt.value/max)*(H-54),...pt})),path=coords.map((c,i)=>`${i?"L":"M"}${c.x},${c.y}`).join(" "),area=`${path} L${coords.at(-1).x},${H-28} L${coords[0].x},${H-28} Z`;$("#projectionChart").innerHTML=`<svg viewBox="0 0 ${W} ${H}" preserveAspectRatio="none"><path d="${area}" fill="rgba(79,209,163,.10)"/><path d="${path}" fill="none" stroke="#4fd1a3" stroke-width="3" stroke-linecap="round" stroke-linejoin="round"/>${coords.map((c,i)=>`<circle cx="${c.x}" cy="${c.y}" r="4" fill="#07111f" stroke="#4fd1a3" stroke-width="2"/><text x="${c.x}" y="${H-8}" text-anchor="middle" fill="#7f95ac" font-size="10">${i===0?"Hoje":c.years+"a"}</text>`).join("")}</svg>`;$("#projectionSummary").innerHTML=[5,10,20].map(y=>`<div><span>${y} anos</span><strong>${compact.format(project(rate,y,p.netWorth,monthly))}</strong></div>`).join("")}
function txRow(t){return`<div class="list-row"><div class="list-icon">${iconFor(t.category)}</div><div class="list-main"><strong>${esc(t.description||t.category)}</strong><small>${esc(t.category)} · ${formatDate(t.date)}</small></div><div><div class="money ${t.type}">${t.type==="expense"?"−":"+"}${currency.format(Number(t.amount||0))}</div><div class="row-actions"><button class="mini-btn" data-delete-tx="${t.id}">Excluir</button></div></div></div>`}
function formatDate(v){if(!v)return"";const[y,m,d]=v.split("-");return`${d}/${m}/${y}`}
function renderTransactions(){const type=$("#txTypeFilter").value,search=$("#txSearch").value.trim().toLowerCase();let list=monthTransactions();if(type!=="all")list=list.filter(t=>t.type===type);if(search)list=list.filter(t=>(t.description||"").toLowerCase().includes(search)||(t.category||"").toLowerCase().includes(search));$("#transactionsList").className="list panel";$("#transactionsList").innerHTML=list.map(txRow).join("")||`<div class="empty-state">Nenhum lançamento.</div>`}
function renderPositions(){const p=calcPositions();$("#assetsTotal").textContent=currency.format(p.assets);$("#debtsTotal").textContent=currency.format(p.debts);$("#patrimonyNetWorth").textContent=currency.format(p.netWorth);$("#positionsList").className="list";$("#positionsList").innerHTML=positionsCache.map(x=>`<div class="list-row"><div class="list-icon">${x.type==="debt"?"−":x.type==="reserve"?"◆":"+"}</div><div class="list-main"><strong>${esc(x.name)}</strong><small>${x.type==="debt"?"Dívida":x.type==="reserve"?"Reserva":"Ativo"}</small></div><div><div class="money ${x.type==="debt"?"expense":"income"}">${currency.format(Number(x.value||0))}</div><div class="row-actions"><button class="mini-btn" data-delete-position="${x.id}">Excluir</button></div></div></div>`).join("")||`<div class="empty-state">Nenhuma posição cadastrada.</div>`}
function renderPlanning(){$("#monthlyContributionGoal").value=settings.monthlyContributionGoal??"";$("#financialFreedomMonthlyCost").value=settings.financialFreedomMonthlyCost??"";$("#realReturn").value=settings.realReturn??5;$("#reserveTargetMonths").value=settings.reserveTargetMonths??6;const p=calcPositions(),monthly=Number(settings.monthlyContributionGoal||Math.max(0,calcMonth().balance)),rate=Number(settings.realReturn??5);$("#projectionGrid").innerHTML=[5,10,20,30].map(y=>`<div class="projection-item"><span>${y} anos</span><strong>${currency.format(project(rate,y,p.netWorth,monthly))}</strong></div>`).join("");const avg=rollingAverageExpenses(),rm=avg?p.reserve/avg:0,targetM=Number(settings.reserveTargetMonths||6),m=calcMonth(),items=[];if(p.debts>0)items.push(`Dívidas registradas em <b>${currency.format(p.debts)}</b>. Compare o CET com o retorno líquido e sem risco antes de decidir entre amortizar e investir.`);if(avg&&rm<targetM)items.push(`Sua reserva cobre <b>${rm.toFixed(1)} meses</b>; a meta está em ${targetM}. Liquidez deve preceder aumento de risco.`);else if(avg&&rm>=targetM)items.push(`A reserva de emergência está compatível com a meta de ${targetM} meses.`);if(m.income>0)items.push(`Taxa de poupança atual: <b>${m.savingRate.toFixed(1)}%</b>. Essa é uma das variáveis de maior impacto na data de independência.`);if(!items.length)items.push(`Cadastre receitas, despesas e posições para liberar o diagnóstico estratégico.`);$("#diagnosis").innerHTML=items.map(x=>`<div class="diagnosis-item">${x}</div>`).join("")}
function fillCategories(type){$("#transactionCategory").innerHTML=categories[type].map(c=>`<option value="${c}">${c}</option>`).join("")}
function openTransaction(){fillCategories("expense");$("#transactionType").value="expense";$$('[data-tx-type]').forEach(b=>b.classList.toggle("selected",b.dataset.txType==="expense"));$("#transactionDate").value=ymd(new Date());$("#transactionAmount").value="";$("#transactionDescription").value="";$("#transactionRecurring").checked=false;$("#transactionDialog").showModal();setTimeout(()=>$("#transactionAmount").focus(),100)}
function switchPage(page){$$('.page').forEach(p=>p.classList.toggle('active',p.id===`${page}Section`));$$('.nav-item').forEach(n=>n.classList.toggle('active',n.dataset.page===page));if(page==="transactions")renderTransactions();if(page==="patrimony")renderPositions();if(page==="planning")renderPlanning();window.scrollTo({top:0,behavior:"smooth"})}
$("#loginForm").addEventListener("submit",async e=>{e.preventDefault();try{await signInWithEmailAndPassword(auth,$("#email").value.trim(),$("#password").value);toast("Acesso liberado")}catch(err){console.error(err);toast("E-mail ou senha inválidos")}});
$("#resetPasswordBtn").addEventListener("click",async()=>{const email=$("#email").value.trim();if(!email)return toast("Informe seu e-mail primeiro");try{await sendPasswordResetEmail(auth,email);toast("E-mail de redefinição enviado")}catch(e){console.error(e);toast("Não foi possível enviar agora")}});
$("#logoutBtn").addEventListener("click",()=>signOut(auth));$("#quickAddBtn").addEventListener("click",openTransaction);$("#openTransactionBtn").addEventListener("click",openTransaction);$$('.close-dialog').forEach(b=>b.addEventListener('click',()=>b.closest('dialog').close()));
$$('[data-tx-type]').forEach(b=>b.addEventListener('click',()=>{const type=b.dataset.txType;$("#transactionType").value=type;fillCategories(type);$$('[data-tx-type]').forEach(x=>x.classList.toggle('selected',x===b))}));
$("#transactionForm").addEventListener("submit",async e=>{e.preventDefault();const amount=Number($("#transactionAmount").value);if(!(amount>0))return toast("Informe um valor válido");try{await addDoc(userCol("transactions"),{type:$("#transactionType").value,amount,category:$("#transactionCategory").value,description:$("#transactionDescription").value.trim(),date:$("#transactionDate").value,recurring:$("#transactionRecurring").checked,createdAt:serverTimestamp()});$("#transactionDialog").close();await loadTransactions();renderAll();toast("Lançamento salvo")}catch(err){console.error(err);toast("Falha ao salvar")}});
$("#openPositionBtn").addEventListener("click",()=>{$("#positionForm").reset();$("#positionDialog").showModal()});
$("#positionForm").addEventListener("submit",async e=>{e.preventDefault();const value=Number($("#positionValue").value);if(value<0)return;try{await addDoc(userCol("positions"),{type:$("#positionType").value,name:$("#positionName").value.trim(),value,createdAt:serverTimestamp()});$("#positionDialog").close();await loadPositions();renderAll();toast("Posição salva")}catch(err){console.error(err);toast("Falha ao salvar posição")}});
$("#planningForm").addEventListener("submit",async e=>{e.preventDefault();settings={monthlyContributionGoal:Number($("#monthlyContributionGoal").value||0),financialFreedomMonthlyCost:Number($("#financialFreedomMonthlyCost").value||0),realReturn:Number($("#realReturn").value||5),reserveTargetMonths:Number($("#reserveTargetMonths").value||6),updatedAt:serverTimestamp()};try{await setDoc(userDoc("config","planning"),settings,{merge:false});await loadSettings();renderAll();toast("Estratégia atualizada")}catch(err){console.error(err);toast("Falha ao salvar planejamento")}});
$("#transactionsList").addEventListener("click",handleDelete);$("#recentTransactions").addEventListener("click",handleDelete);$("#positionsList").addEventListener("click",handleDelete);
async function handleDelete(e){const tx=e.target.dataset.deleteTx,pos=e.target.dataset.deletePosition;if(tx&&confirm("Excluir este lançamento?")){await deleteDoc(userDoc("transactions",tx));await loadTransactions();renderAll();toast("Lançamento excluído")}if(pos&&confirm("Excluir esta posição?")){await deleteDoc(userDoc("positions",pos));await loadPositions();renderAll();toast("Posição excluída")}}
$("#txTypeFilter").addEventListener("change",renderTransactions);$("#txSearch").addEventListener("input",renderTransactions);$("#prevMonth").addEventListener("click",()=>{selectedMonth.setMonth(selectedMonth.getMonth()-1);renderAll()});$("#nextMonth").addEventListener("click",()=>{selectedMonth.setMonth(selectedMonth.getMonth()+1);renderAll()});$$('.nav-item').forEach(n=>n.addEventListener('click',()=>switchPage(n.dataset.page)));$$('[data-go]').forEach(b=>b.addEventListener('click',()=>switchPage(b.dataset.go)));
onAuthStateChanged(auth,async u=>{if(u){user=u;$("#authView").classList.add("hidden");$("#appView").classList.remove("hidden");try{await loadAll()}catch(err){console.error(err);toast("Falha ao carregar os dados")}}else{user=null;$("#authView").classList.remove("hidden");$("#appView").classList.add("hidden")}});
if("serviceWorker" in navigator) navigator.serviceWorker.register("./sw.js").catch(console.warn);
