import { initializeApp } from "https://www.gstatic.com/firebasejs/12.17.0/firebase-app.js";
import { getAuth, signInWithEmailAndPassword, signOut, onAuthStateChanged, sendPasswordResetEmail, browserLocalPersistence, setPersistence } from "https://www.gstatic.com/firebasejs/12.17.0/firebase-auth.js";
import { getFirestore, collection, doc, addDoc, setDoc, getDoc, getDocs, deleteDoc, updateDoc, query, orderBy, serverTimestamp } from "https://www.gstatic.com/firebasejs/12.17.0/firebase-firestore.js";
import { initializeAppCheck, ReCaptchaEnterpriseProvider } from "https://www.gstatic.com/firebasejs/12.17.0/firebase-app-check.js";
import { firebaseConfig, appCheckSiteKey } from "./firebase-config.js";

const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const currency=new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'});
const compact=new Intl.NumberFormat('pt-BR',{notation:'compact',maximumFractionDigits:1});
const monthFmt=new Intl.DateTimeFormat('pt-BR',{month:'long',year:'numeric'});
const categories={expense:['Moradia','Mercado','Restaurantes','Transporte','Veículo','Saúde','Academia','Pets','Assinaturas','Lazer','Compras','Impostos','Seguros','Educação','Viagens','Outros'],income:['Salário','Benefícios','Renda extra','Investimentos','Reembolso','Venda','Outros']};
const palette=['#4fd1a3','#6ea8ff','#f7c65d','#ff7d86','#a78bfa','#5eead4','#fb923c','#94a3b8'];

const app=initializeApp(firebaseConfig);
if(appCheckSiteKey) initializeAppCheck(app,{provider:new ReCaptchaEnterpriseProvider(appCheckSiteKey),isTokenAutoRefreshEnabled:true});
const auth=getAuth(app), db=getFirestore(app); await setPersistence(auth,browserLocalPersistence);
let user=null,selectedMonth=new Date(),selectedYear=new Date().getFullYear();selectedMonth.setDate(1);
let txCache=[],positionsCache=[],recurringCache=[],scheduledCache=[],settings={},agendaAvailable=true;

function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2400)}
function ymd(d){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function monthKey(d){return ymd(d).slice(0,7)}
function esc(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function formatDate(v){if(!v)return'';const [y,m,d]=v.split('-');return `${d}/${m}/${y}`}
function userCol(name){return collection(db,'users',user.uid,name)}
function userDoc(name,id){return doc(db,'users',user.uid,name,id)}
function clamp(v,min,max){return Math.min(max,Math.max(min,v))}
function monthTransactions(date=selectedMonth){const k=monthKey(date);return txCache.filter(t=>String(t.date||'').startsWith(k))}
function calcMonth(date=selectedMonth){const txs=monthTransactions(date),income=txs.filter(t=>t.type==='income').reduce((s,t)=>s+Number(t.amount||0),0),expense=txs.filter(t=>t.type==='expense').reduce((s,t)=>s+Number(t.amount||0),0);return{txs,income,expense,balance:income-expense,savingRate:income?(income-expense)/income*100:0}}
function calcPositions(){const assets=positionsCache.filter(p=>['asset','reserve'].includes(p.type)).reduce((s,p)=>s+Number(p.value||0),0),reserve=positionsCache.filter(p=>p.type==='reserve').reduce((s,p)=>s+Number(p.value||0),0),debts=positionsCache.filter(p=>p.type==='debt').reduce((s,p)=>s+Number(p.value||0),0);return{assets,reserve,debts,netWorth:assets-debts}}
function rollingAverageExpenses(){const map={};txCache.filter(t=>t.type==='expense').forEach(t=>{const k=String(t.date||'').slice(0,7);if(/^\d{4}-\d{2}$/.test(k))map[k]=(map[k]||0)+Number(t.amount||0)});const vals=Object.keys(map).sort().reverse().slice(0,6).map(k=>map[k]);return vals.length?vals.reduce((a,b)=>a+b,0)/vals.length:0}
function monthLabel(d){return monthFmt.format(d).replace(/^./,c=>c.toUpperCase())}
function daysElapsedInMonth(date){const now=new Date();if(date.getFullYear()!==now.getFullYear()||date.getMonth()!==now.getMonth())return new Date(date.getFullYear(),date.getMonth()+1,0).getDate();return now.getDate()}
function nextMonthDate(dateStr){const [y,m,d]=dateStr.split('-').map(Number);const x=new Date(y,m,d);const day=Math.min(d,new Date(x.getFullYear(),x.getMonth()+1,0).getDate());x.setDate(day);return ymd(x)}
function addYear(dateStr){const [y,m,d]=dateStr.split('-').map(Number);const last=new Date(y+1,m,0).getDate();return `${y+1}-${String(m).padStart(2,'0')}-${String(Math.min(d,last)).padStart(2,'0')}`}
function dueDateFor(y,m,day){const last=new Date(y,m+1,0).getDate();return `${y}-${String(m+1).padStart(2,'0')}-${String(Math.min(day,last)).padStart(2,'0')}`}

async function ensureUserRoot(){const ref=doc(db,'users',user.uid),snap=await getDoc(ref);if(!snap.exists())await setDoc(ref,{createdAt:serverTimestamp(),email:user.email})}
async function loadCollection(name,sortField){const snap=sortField?await getDocs(query(userCol(name),orderBy(sortField,'desc'))):await getDocs(userCol(name));return snap.docs.map(d=>({id:d.id,...d.data()}))}
async function loadAll(){await ensureUserRoot();txCache=await loadCollection('transactions','date');positionsCache=await loadCollection('positions','createdAt');const s=await getDoc(userDoc('config','planning'));settings=s.exists()?s.data():{};try{recurringCache=await loadCollection('recurring','createdAt');scheduledCache=await loadCollection('scheduled','dueDate');agendaAvailable=true}catch(e){console.warn('Agenda indisponível até atualizar regras',e);recurringCache=[];scheduledCache=[];agendaAvailable=false}if(agendaAvailable){await migrateLegacyRecurring();recurringCache=await loadCollection('recurring','createdAt');await processAutomations();txCache=await loadCollection('transactions','date');recurringCache=await loadCollection('recurring','createdAt');scheduledCache=await loadCollection('scheduled','dueDate')}renderAll()}

async function migrateLegacyRecurring(){for(const t of txCache.filter(x=>x.recurring===true&&!x.sourceType)){const id=`legacy_${t.id}`,ref=userDoc('recurring',id);if((await getDoc(ref)).exists())continue;await setDoc(ref,{name:t.description||t.category,type:t.type,amount:Number(t.amount),category:t.category,description:t.description||'',dayOfMonth:Number(String(t.date).slice(8,10)),startDate:nextMonthDate(t.date),endDate:'',active:true,createdAt:serverTimestamp(),updatedAt:serverTimestamp()})}}
async function processAutomations(){const today=ymd(new Date());for(const r of recurringCache.filter(x=>x.active)){const [sy,sm]=r.startDate.split('-').map(Number);let cursor=new Date(sy,sm-1,1),guard=0;while(guard++<120){const due=dueDateFor(cursor.getFullYear(),cursor.getMonth(),Number(r.dayOfMonth));if(due>today)break;if(r.endDate&&due>r.endDate)break;const id=`rec_${r.id}_${due.slice(0,7)}`,ref=userDoc('transactions',id);if(!(await getDoc(ref)).exists())await setDoc(ref,{type:r.type,amount:Number(r.amount),category:r.category,description:r.name||r.description||'',date:due,recurring:true,sourceType:'recurring',sourceId:r.id,createdAt:serverTimestamp()});cursor.setMonth(cursor.getMonth()+1)}}
for(const s of scheduledCache.filter(x=>x.status==='active')){let due=s.dueDate,guard=0;while(due&&due<=today&&guard++<10){const id=s.frequency==='annual'?`sched_${s.id}_${due.slice(0,4)}`:`sched_${s.id}`,ref=userDoc('transactions',id);if(!(await getDoc(ref)).exists())await setDoc(ref,{type:s.type,amount:Number(s.amount),category:s.category,description:s.name||s.description||'',date:due,recurring:false,sourceType:'scheduled',sourceId:s.id,createdAt:serverTimestamp()});if(s.frequency==='annual'){due=addYear(due);await updateDoc(userDoc('scheduled',s.id),{dueDate:due,updatedAt:serverTimestamp()})}else{await updateDoc(userDoc('scheduled',s.id),{status:'posted',updatedAt:serverTimestamp()});break}}}}

function renderAll(){renderDashboard();renderTransactions();renderAnnual();renderAgenda();renderPositions();renderPlanning()}
function renderDashboard(){const m=calcMonth(),p=calcPositions(),prevDate=new Date(selectedMonth);prevDate.setMonth(prevDate.getMonth()-1);const prev=calcMonth(prevDate),avg=rollingAverageExpenses(),reserveMonths=avg?p.reserve/avg:0,targetMonthly=Number(settings.financialFreedomMonthlyCost||0),freedomTarget=targetMonthly?targetMonthly*12/.04:0,freedom=freedomTarget?clamp(p.netWorth/freedomTarget*100,0,100):0;$('#monthLabel').textContent=monthLabel(selectedMonth);$('#netWorth').textContent=currency.format(p.netWorth);$('#freedomBadge').textContent=`${freedom.toFixed(1)}% da liberdade`;$('#monthBalance').textContent=currency.format(m.balance);$('#savingRate').textContent=`${m.savingRate.toFixed(1)}%`;$('#reserveMonths').textContent=`${reserveMonths.toFixed(1)} meses`;$('#reserveValue').textContent=currency.format(p.reserve);$('#debtValue').textContent=currency.format(p.debts);$('#debtRatio').textContent=`${(p.assets?p.debts/p.assets*100:0).toFixed(1)}% dos ativos`;$('#balanceTrend').textContent=prev.balance===0?'Sem base anterior':`${m.balance>=prev.balance?'▲':'▼'} ${currency.format(Math.abs(m.balance-prev.balance))} vs. mês anterior`;$('#savingStatus').textContent=m.savingRate>=20?'Meta de 20% atingida':'Abaixo da referência de 20%';$('#freedomPercent').textContent=`${freedom.toFixed(1)}%`;$('#freedomRing').style.setProperty('--p',`${freedom}%`);$('#freedomTarget').textContent=freedomTarget?currency.format(freedomTarget):'Defina a meta';$('#freedomGap').textContent=freedomTarget?currency.format(Math.max(0,freedomTarget-p.netWorth)):'—';renderScoreAndPet(m,p,reserveMonths);renderCashflow();renderDonut(m);renderInsights(m,p,reserveMonths);renderMissions(m,p,reserveMonths);renderUpcoming();$('#recentTransactions').innerHTML=m.txs.slice(0,6).map(txRow).join('')||'<div class="empty-state">Nenhum lançamento.</div>'}

function renderScoreAndPet(m,p,reserveMonths){const surplusGoal=Number(settings.monthlySurplusGoal||0),dailyGoal=Number(settings.dailySpendGoal||0),reserveTarget=Number(settings.reserveTargetMonths||6),dailyAvg=m.expense/Math.max(1,daysElapsedInMonth(selectedMonth)),debtRatio=p.assets?p.debts/p.assets:0;const parts={sobra:surplusGoal?clamp(m.balance/surplusGoal,0,1):.5,diario:dailyGoal?clamp(dailyGoal/Math.max(dailyAvg,.01),0,1):.5,reserva:clamp(reserveMonths/reserveTarget,0,1),divida:debtRatio<=.25?1:debtRatio<=.5?.55:.2,planejamento:(surplusGoal&&dailyGoal&&Number(settings.financialFreedomMonthlyCost||0))?1:.4};const health=Math.round(parts.sobra*30+parts.diario*25+parts.reserva*20+parts.divida*15+parts.planejamento*10);const score=Math.round(health*.75+clamp(m.savingRate/30,0,1)*25);$('#financeScore').textContent=score;$('#scoreRing').style.setProperty('--p',`${score}%`);$('#scoreLabel').textContent=score>=85?'Excelente':score>=70?'Forte':score>=50?'Em evolução':'Atenção';$('#scoreHint').textContent=score>=70?'Seu sistema financeiro está bem disciplinado.':'As metas abaixo mostram onde ganhar pontos.';const xp=Math.max(0,txCache.length*2+(m.savingRate>=20?100:0)+(health>=80?150:0)+(reserveMonths>=reserveTarget?200:0));$('#xpPill').textContent=`${xp} XP`;$('#levelPill').textContent=`Nível ${Math.max(1,Math.floor(xp/250)+1)}`;
let avatar='🐷',state='Cansado',msg='Estou precisando de mais disciplina financeira.';if(health>=85){avatar='🐷✨';state='Radiante';msg='Estou excelente! Suas metas, reserva e gastos estão bem equilibrados.'}else if(health>=70){avatar='🐷';state='Saudável';msg='Estou saudável. Continue protegendo a sobra mensal e o limite diário.'}else if(health>=50){avatar='🐽';state='Em atenção';msg='Estou razoável, mas uma ou duas metas estão pressionando minha saúde.'}else if(health<30){avatar='😵‍💫';state='Crítico';msg='Preciso de cuidados: priorize caixa, limite diário e redução de pressão financeira.'}$('#petAvatar').textContent=avatar;$('#petName').textContent=`Cofrinho · ${state}`;$('#petMessage').textContent=msg;$('#petHealthBadge').textContent=`Saúde ${health}%`;$('#petHealthBadge').className=`health-badge ${health>=70?'good':health>=45?'warn':'bad'}`;$('#petHealthBar').style.width=`${health}%`;$('#petVitals').innerHTML=[['Sobra',Math.round(parts.sobra*100)+'%'],['Gasto diário',Math.round(parts.diario*100)+'%'],['Reserva',Math.round(parts.reserva*100)+'%'],['Dívidas',Math.round(parts.divida*100)+'%']].map(([a,b])=>`<div><span>${a}</span><strong>${b}</strong></div>`).join('');$('#surplusGoalStatus').textContent=surplusGoal?currency.format(m.balance):'—';$('#surplusGoalDetail').textContent=surplusGoal?`Meta: ${currency.format(surplusGoal)}`:'Defina no planejamento';$('#dailyGoalStatus').textContent=dailyGoal?currency.format(dailyAvg):'—';$('#dailyGoalDetail').textContent=dailyGoal?`Média/dia · limite ${currency.format(dailyGoal)}`:'Defina no planejamento'}

function txRow(t){const src=t.sourceType==='recurring'?' · recorrente':t.sourceType==='scheduled'?' · agendada':'';return `<div class="list-row"><div class="list-icon">${t.type==='expense'?'−':'+'}</div><div class="list-main"><strong>${esc(t.description||t.category)}</strong><small>${esc(t.category)} · ${formatDate(t.date)}${src}</small></div><div><div class="money ${t.type}">${t.type==='expense'?'−':'+'}${currency.format(Number(t.amount||0))}</div><div class="row-actions"><button class="mini-btn danger" data-delete-tx="${t.id}">Excluir</button></div></div></div>`}
function renderTransactions(){const type=$('#txTypeFilter').value,search=$('#txSearch').value.trim().toLowerCase();let list=monthTransactions();if(type!=='all')list=list.filter(t=>t.type===type);if(search)list=list.filter(t=>(t.description||'').toLowerCase().includes(search)||(t.category||'').toLowerCase().includes(search));$('#transactionsList').innerHTML=list.map(txRow).join('')||'<div class="empty-state">Nenhum lançamento.</div>'}
function renderCashflow(){const rows=[];for(let i=5;i>=0;i--){const d=new Date(selectedMonth);d.setMonth(d.getMonth()-i);const m=calcMonth(d);rows.push({label:d.toLocaleDateString('pt-BR',{month:'short'}).replace('.',''),income:m.income,expense:m.expense})}$('#cashflowChart').innerHTML=barSvg(rows)}
function barSvg(rows){const max=Math.max(1,...rows.flatMap(r=>[r.income,r.expense])),w=720,h=230,pad=30,group=(w-pad*2)/rows.length,bw=Math.max(6,group*.23);return `<svg viewBox="0 0 ${w} ${h}" role="img">${rows.map((r,i)=>{const x=pad+i*group+group*.25,ih=r.income/max*(h-60),eh=r.expense/max*(h-60);return `<rect x="${x}" y="${h-30-ih}" width="${bw}" height="${ih}" rx="5" fill="#58d6a2"/><rect x="${x+bw+5}" y="${h-30-eh}" width="${bw}" height="${eh}" rx="5" fill="#ff7d86"/><text x="${x+group*.22}" y="${h-8}" fill="#8fa2b8" font-size="11" text-anchor="middle">${r.label}</text>`}).join('')}</svg>`}
function renderDonut(m){const cats={};m.txs.filter(t=>t.type==='expense').forEach(t=>cats[t.category]=(cats[t.category]||0)+Number(t.amount));const rows=Object.entries(cats).sort((a,b)=>b[1]-a[1]),total=m.expense||1;let pos=0;const stops=[];rows.slice(0,8).forEach(([c,v],i)=>{const end=pos+v/total*100;stops.push(`${palette[i%palette.length]} ${pos}% ${end}%`);pos=end});$('#expenseDonut').style.setProperty('--donut',rows.length?`conic-gradient(${stops.join(',')})`:'conic-gradient(#1c2e40 0 100%)');$('#expenseTotal').textContent=compact.format(m.expense);$('#categoryLegend').innerHTML=rows.slice(0,6).map(([c,v],i)=>`<div class="category-item"><i class="category-swatch" style="background:${palette[i%palette.length]}"></i><span>${esc(c)}</span><b>${currency.format(v)}</b></div>`).join('')||'<div class="muted">Sem despesas.</div>'}
function renderInsights(m,p,reserveMonths){const insights=[];const prev=new Date(selectedMonth);prev.setMonth(prev.getMonth()-1);const pm=calcMonth(prev);if(pm.expense>0){const delta=(m.expense-pm.expense)/pm.expense*100;insights.push([delta<=0?'📉':'📈','Despesas vs. mês anterior',`${delta>=0?'+':''}${delta.toFixed(1)}% de variação.`])}const cats={};m.txs.filter(t=>t.type==='expense').forEach(t=>cats[t.category]=(cats[t.category]||0)+Number(t.amount));const top=Object.entries(cats).sort((a,b)=>b[1]-a[1])[0];if(top)insights.push(['🎯','Maior categoria',`${top[0]} consumiu ${(m.expense?top[1]/m.expense*100:0).toFixed(1)}% das despesas.`]);insights.push(['🛟','Reserva',reserveMonths?`Cobertura estimada de ${reserveMonths.toFixed(1)} meses.`:'Cadastre a reserva e seu histórico de despesas.']);if(Number(settings.dailySpendGoal||0)){const avg=m.expense/Math.max(1,daysElapsedInMonth(selectedMonth));insights.push([avg<=settings.dailySpendGoal?'✅':'⚠️','Ritmo diário',`Média de ${currency.format(avg)}/dia vs. meta de ${currency.format(settings.dailySpendGoal)}.`])}$('#insightsList').innerHTML=insights.map(x=>`<div class="insight"><div class="insight-icon">${x[0]}</div><div><strong>${x[1]}</strong><p>${x[2]}</p></div></div>`).join('')}
function renderMissions(m,p,reserveMonths){const surplus=Number(settings.monthlySurplusGoal||0),daily=Number(settings.dailySpendGoal||0),avg=m.expense/Math.max(1,daysElapsedInMonth(selectedMonth)),target=Number(settings.reserveTargetMonths||6);const missions=[['💰','Sobra mensal',surplus?`${currency.format(m.balance)} / ${currency.format(surplus)}`:'Defina uma meta',surplus?clamp(m.balance/surplus,0,1):0],['🧭','Ritmo diário',daily?`${currency.format(avg)} / ${currency.format(daily)} por dia`:'Defina um limite',daily?clamp(daily/Math.max(avg,.01),0,1):0],['🛟','Reserva de segurança',`${reserveMonths.toFixed(1)} / ${target} meses`,clamp(reserveMonths/target,0,1)],['📉','Alavancagem saudável',`${(p.assets?p.debts/p.assets*100:0).toFixed(1)}% de dívida/ativos`,p.assets?clamp(1-p.debts/p.assets,0,1):1]];$('#missionsList').innerHTML=missions.map(([i,n,d,pct])=>`<div class="mission ${pct>=1?'done':''}"><div class="mission-icon">${i}</div><div><strong>${n}</strong><p>${d}</p><div class="mission-progress"><i style="width:${pct*100}%"></i></div></div></div>`).join('')}
function renderUpcoming(){if(!agendaAvailable){$('#upcomingList').innerHTML='<div class="muted">Atualize as regras do Firestore para ativar a agenda.</div>';return}const today=ymd(new Date()),limit=new Date();limit.setDate(limit.getDate()+45);const end=ymd(limit),rows=[];scheduledCache.filter(s=>s.status==='active'&&s.dueDate>=today&&s.dueDate<=end).forEach(s=>rows.push({date:s.dueDate,name:s.name,amount:s.amount,icon:'📅'}));recurringCache.filter(r=>r.active).forEach(r=>{const n=new Date(),d=dueDateFor(n.getFullYear(),n.getMonth(),r.dayOfMonth);if(d>=today&&d<=end)rows.push({date:d,name:r.name,amount:r.amount,icon:'🔁'})});rows.sort((a,b)=>a.date.localeCompare(b.date));$('#upcomingList').innerHTML=rows.slice(0,5).map(x=>`<div class="agenda-item"><div class="agenda-icon">${x.icon}</div><div><strong>${esc(x.name)}</strong><small>${formatDate(x.date)}</small></div><b>${currency.format(x.amount)}</b></div>`).join('')||'<div class="muted">Nada nos próximos 45 dias.</div>'}

function renderAnnual(){selectedYear=Number(selectedYear);$('#yearLabel').textContent=selectedYear;const rows=[],cats={};let income=0,expense=0;for(let m=0;m<12;m++){const d=new Date(selectedYear,m,1),x=calcMonth(d);rows.push({label:d.toLocaleDateString('pt-BR',{month:'short'}).replace('.',''),income:x.income,expense:x.expense,balance:x.balance});income+=x.income;expense+=x.expense;x.txs.filter(t=>t.type==='expense').forEach(t=>cats[t.category]=(cats[t.category]||0)+Number(t.amount))}$('#annualIncome').textContent=currency.format(income);$('#annualExpense').textContent=currency.format(expense);$('#annualBalance').textContent=currency.format(income-expense);$('#annualSavingRate').textContent=`${income?((income-expense)/income*100).toFixed(1):0}%`;$('#annualChart').innerHTML=barSvg(rows);const cr=Object.entries(cats).sort((a,b)=>b[1]-a[1]),max=cr[0]?.[1]||1;$('#annualCategories').innerHTML=cr.slice(0,10).map(([c,v],i)=>`<div class="rank-item"><div><strong>${i+1}. ${esc(c)}</strong><small>${currency.format(v)}</small><div class="rank-bar"><i style="width:${v/max*100}%"></i></div></div><b>${expense?Math.round(v/expense*100):0}%</b></div>`).join('')||'<div class="muted">Sem dados.</div>';$('#annualMonths').innerHTML=rows.map(r=>`<div class="month-item"><div><strong>${r.label.toUpperCase()}</strong><small>R ${compact.format(r.income)} · D ${compact.format(r.expense)}</small></div><b class="money ${r.balance>=0?'income':'expense'}">${currency.format(r.balance)}</b></div>`).join('')}

function renderAgenda(){if(!agendaAvailable){$('#automationNotice').classList.remove('hidden');$('#automationNotice').textContent='A interface já está pronta, mas o Firebase ainda precisa receber as novas regras para liberar recorrências e contas agendadas.';$('#recurringList').innerHTML=$('#scheduledList').innerHTML='<div class="empty-state">Aguardando regras.</div>';return}$('#automationNotice').classList.add('hidden');$('#recurringCount').textContent=`${recurringCache.filter(r=>r.active).length} ativas`;$('#scheduledCount').textContent=`${scheduledCache.filter(s=>s.status==='active').length} futuras`;$('#recurringList').innerHTML=recurringCache.map(r=>`<div class="agenda-item ${r.active?'':'inactive'}"><div class="agenda-icon">🔁</div><div><strong>${esc(r.name)}</strong><small>${currency.format(r.amount)} · dia ${r.dayOfMonth} · ${esc(r.category)}</small></div><div class="agenda-actions"><button class="mini-btn" data-edit-rec="${r.id}">Editar</button><button class="mini-btn danger" data-del-rec="${r.id}">Excluir</button></div></div>`).join('')||'<div class="empty-state">Nenhuma recorrência.</div>';$('#scheduledList').innerHTML=scheduledCache.map(s=>`<div class="agenda-item ${s.status==='active'?'':'inactive'}"><div class="agenda-icon">📅</div><div><strong>${esc(s.name)}</strong><small>${currency.format(s.amount)} · ${formatDate(s.dueDate)} · ${s.frequency==='annual'?'anual':s.status==='posted'?'lançada':'uma vez'}</small></div><div class="agenda-actions">${s.status==='active'?`<button class="mini-btn" data-edit-sch="${s.id}">Editar</button>`:''}<button class="mini-btn danger" data-del-sch="${s.id}">Excluir</button></div></div>`).join('')||'<div class="empty-state">Nenhuma conta agendada.</div>'}
function renderPositions(){const p=calcPositions();$('#assetsTotal').textContent=currency.format(p.assets);$('#debtsTotal').textContent=currency.format(p.debts);$('#patrimonyNetWorth').textContent=currency.format(p.netWorth);$('#positionsList').innerHTML=positionsCache.map(x=>`<div class="list-row"><div class="list-icon">${x.type==='debt'?'−':'+'}</div><div class="list-main"><strong>${esc(x.name)}</strong><small>${x.type==='debt'?'Dívida':x.type==='reserve'?'Reserva':'Ativo'}</small></div><div><div class="money ${x.type==='debt'?'expense':'income'}">${currency.format(Number(x.value||0))}</div><div class="row-actions"><button class="mini-btn danger" data-delete-position="${x.id}">Excluir</button></div></div></div>`).join('')||'<div class="empty-state">Nenhuma posição.</div>'}
function project(rate,years,start,monthly){const r=Math.pow(1+rate/100,1/12)-1,n=years*12;return start*Math.pow(1+r,n)+(r?monthly*(Math.pow(1+r,n)-1)/r:monthly*n)}
function renderPlanning(){['monthlyContributionGoal','monthlySurplusGoal','dailySpendGoal','financialFreedomMonthlyCost','realReturn','reserveTargetMonths'].forEach(id=>{$('#'+id).value=settings[id]??(id==='realReturn'?5:id==='reserveTargetMonths'?6:'')});const p=calcPositions(),monthly=Number(settings.monthlyContributionGoal||Math.max(0,calcMonth().balance)),rate=Number(settings.realReturn??5);$('#projectionGrid').innerHTML=[5,10,20,30].map(y=>`<div class="projection-item"><span>${y} anos</span><strong>${currency.format(project(rate,y,p.netWorth,monthly))}</strong></div>`).join('');const avg=rollingAverageExpenses(),rm=avg?p.reserve/avg:0,items=[];if(p.debts>0)items.push(`Dívidas registradas: <b>${currency.format(p.debts)}</b>. Compare o CET com o retorno líquido dos investimentos.`);if(avg)items.push(`Reserva atual cobre <b>${rm.toFixed(1)} meses</b>; meta: ${Number(settings.reserveTargetMonths||6)} meses.`);if(Number(settings.monthlySurplusGoal||0))items.push(`Sua meta é encerrar cada mês com pelo menos <b>${currency.format(settings.monthlySurplusGoal)}</b> de sobra.`);if(Number(settings.dailySpendGoal||0))items.push(`Seu teto médio diário está definido em <b>${currency.format(settings.dailySpendGoal)}</b>.`);$('#diagnosis').innerHTML=(items.length?items:['Cadastre metas e patrimônio para liberar o diagnóstico.']).map(x=>`<div class="diagnosis-item">${x}</div>`).join('')}

function fillCategories(select,type){select.innerHTML=categories[type].map(c=>`<option value="${c}">${c}</option>`).join('')}
function openTransaction(){fillCategories($('#transactionCategory'),'expense');$('#transactionType').value='expense';$('#transactionAmount').value='';$('#transactionDescription').value='';$('#transactionDate').value=ymd(new Date());$('#transactionRecurring').checked=false;$$('[data-tx-type]').forEach(b=>b.classList.toggle('selected',b.dataset.txType==='expense'));$('#transactionDialog').showModal()}
function openRecurring(r=null){$('#recurringForm').reset();$('#recurringEditId').value=r?.id||'';$('#recurringDialogTitle').textContent=r?'Editar conta recorrente':'Nova conta recorrente';$('#recurringType').value=r?.type||'expense';fillCategories($('#recurringCategory'),$('#recurringType').value);$('#recurringName').value=r?.name||'';$('#recurringAmount').value=r?.amount||'';$('#recurringCategory').value=r?.category||categories.expense[0];$('#recurringDay').value=r?.dayOfMonth||new Date().getDate();$('#recurringStart').value=r?.startDate||ymd(new Date());$('#recurringEnd').value=r?.endDate||'';$('#recurringActive').checked=r?!!r.active:true;$('#recurringDialog').showModal()}
function openScheduled(s=null){$('#scheduledForm').reset();$('#scheduledEditId').value=s?.id||'';$('#scheduledDialogTitle').textContent=s?'Editar conta agendada':'Nova conta agendada';$('#scheduledType').value=s?.type||'expense';fillCategories($('#scheduledCategory'),$('#scheduledType').value);$('#scheduledName').value=s?.name||'';$('#scheduledAmount').value=s?.amount||'';$('#scheduledCategory').value=s?.category||categories.expense[0];$('#scheduledDue').value=s?.dueDate||ymd(new Date());$('#scheduledFrequency').value=s?.frequency||'once';$('#scheduledDialog').showModal()}
function switchPage(page){$$('.page').forEach(p=>p.classList.toggle('active',p.id===`${page}Section`));$$('.nav-item').forEach(n=>n.classList.toggle('active',n.dataset.page===page));if(page==='annual')renderAnnual();if(page==='agenda')renderAgenda();window.scrollTo({top:0,behavior:'smooth'})}

$('#loginForm').addEventListener('submit',async e=>{e.preventDefault();try{await signInWithEmailAndPassword(auth,$('#email').value.trim(),$('#password').value);toast('Acesso liberado')}catch(e){console.error(e);toast('E-mail ou senha inválidos')}});$('#resetPasswordBtn').addEventListener('click',async()=>{const email=$('#email').value.trim();if(!email)return toast('Informe seu e-mail');try{await sendPasswordResetEmail(auth,email);toast('E-mail de redefinição enviado')}catch(e){toast('Não foi possível enviar agora')}});$('#logoutBtn').addEventListener('click',()=>signOut(auth));
$('#quickAddBtn').addEventListener('click',openTransaction);$('#openTransactionBtn').addEventListener('click',openTransaction);$('#openRecurringBtn').addEventListener('click',()=>openRecurring());$('#openScheduledBtn').addEventListener('click',()=>openScheduled());$$('.close-dialog').forEach(b=>b.addEventListener('click',()=>b.closest('dialog').close()));$$('.nav-item').forEach(b=>b.addEventListener('click',()=>switchPage(b.dataset.page)));$$('[data-go]').forEach(b=>b.addEventListener('click',()=>switchPage(b.dataset.go)));
$('#prevMonth').addEventListener('click',()=>{selectedMonth.setMonth(selectedMonth.getMonth()-1);renderAll()});$('#nextMonth').addEventListener('click',()=>{selectedMonth.setMonth(selectedMonth.getMonth()+1);renderAll()});$('#prevYear').addEventListener('click',()=>{selectedYear--;renderAnnual()});$('#nextYear').addEventListener('click',()=>{selectedYear++;renderAnnual()});$('#txTypeFilter').addEventListener('change',renderTransactions);$('#txSearch').addEventListener('input',renderTransactions);
$$('[data-tx-type]').forEach(b=>b.addEventListener('click',()=>{$('#transactionType').value=b.dataset.txType;fillCategories($('#transactionCategory'),b.dataset.txType);$$('[data-tx-type]').forEach(x=>x.classList.toggle('selected',x===b))}));$('#recurringType').addEventListener('change',()=>fillCategories($('#recurringCategory'),$('#recurringType').value));$('#scheduledType').addEventListener('change',()=>fillCategories($('#scheduledCategory'),$('#scheduledType').value));

$('#transactionForm').addEventListener('submit',async e=>{e.preventDefault();const amount=Number($('#transactionAmount').value),data={type:$('#transactionType').value,amount,category:$('#transactionCategory').value,description:$('#transactionDescription').value.trim(),date:$('#transactionDate').value,recurring:$('#transactionRecurring').checked,createdAt:serverTimestamp()};if(!(amount>0))return toast('Informe um valor válido');const ref=await addDoc(userCol('transactions'),data);if(data.recurring&&agendaAvailable){await setDoc(userDoc('recurring',`legacy_${ref.id}`),{name:data.description||data.category,type:data.type,amount:data.amount,category:data.category,description:data.description,dayOfMonth:Number(data.date.slice(8,10)),startDate:nextMonthDate(data.date),endDate:'',active:true,createdAt:serverTimestamp(),updatedAt:serverTimestamp()})}$('#transactionDialog').close();await loadAll();toast(data.recurring?'Lançamento salvo e recorrência criada':'Lançamento salvo')});
$('#openPositionBtn').addEventListener('click',()=>{$('#positionForm').reset();$('#positionDialog').showModal()});
$('#positionForm').addEventListener('submit',async e=>{e.preventDefault();await addDoc(userCol('positions'),{type:$('#positionType').value,name:$('#positionName').value.trim(),value:Number($('#positionValue').value),createdAt:serverTimestamp()});$('#positionDialog').close();await loadAll();toast('Posição salva')});
$('#planningForm').addEventListener('submit',async e=>{e.preventDefault();settings={monthlyContributionGoal:Number($('#monthlyContributionGoal').value||0),monthlySurplusGoal:Number($('#monthlySurplusGoal').value||0),dailySpendGoal:Number($('#dailySpendGoal').value||0),financialFreedomMonthlyCost:Number($('#financialFreedomMonthlyCost').value||0),realReturn:Number($('#realReturn').value||5),reserveTargetMonths:Number($('#reserveTargetMonths').value||6),updatedAt:serverTimestamp()};await setDoc(userDoc('config','planning'),settings);toast('Estratégia atualizada');await loadAll()});
$('#recurringForm').addEventListener('submit',async e=>{e.preventDefault();const id=$('#recurringEditId').value,data={name:$('#recurringName').value.trim(),type:$('#recurringType').value,amount:Number($('#recurringAmount').value),category:$('#recurringCategory').value,description:$('#recurringName').value.trim(),dayOfMonth:Number($('#recurringDay').value),startDate:$('#recurringStart').value,endDate:$('#recurringEnd').value||'',active:$('#recurringActive').checked,updatedAt:serverTimestamp()};if(id)await updateDoc(userDoc('recurring',id),data);else await addDoc(userCol('recurring'),{...data,createdAt:serverTimestamp()});$('#recurringDialog').close();await loadAll();toast('Recorrência salva')});
$('#scheduledForm').addEventListener('submit',async e=>{e.preventDefault();const id=$('#scheduledEditId').value,data={name:$('#scheduledName').value.trim(),type:$('#scheduledType').value,amount:Number($('#scheduledAmount').value),category:$('#scheduledCategory').value,description:$('#scheduledName').value.trim(),dueDate:$('#scheduledDue').value,frequency:$('#scheduledFrequency').value,status:'active',updatedAt:serverTimestamp()};if(id)await updateDoc(userDoc('scheduled',id),data);else await addDoc(userCol('scheduled'),{...data,createdAt:serverTimestamp()});$('#scheduledDialog').close();await loadAll();toast('Conta agendada salva')});

document.addEventListener('click',async e=>{const t=e.target;if(t.dataset.deleteTx){await deleteDoc(userDoc('transactions',t.dataset.deleteTx));await loadAll();toast('Lançamento excluído')}if(t.dataset.deletePosition){await deleteDoc(userDoc('positions',t.dataset.deletePosition));await loadAll();toast('Posição excluída')}if(t.dataset.editRec)openRecurring(recurringCache.find(x=>x.id===t.dataset.editRec));if(t.dataset.delRec&&confirm('Excluir esta recorrência?')){await deleteDoc(userDoc('recurring',t.dataset.delRec));await loadAll();toast('Recorrência excluída')}if(t.dataset.editSch)openScheduled(scheduledCache.find(x=>x.id===t.dataset.editSch));if(t.dataset.delSch&&confirm('Excluir esta conta agendada?')){await deleteDoc(userDoc('scheduled',t.dataset.delSch));await loadAll();toast('Agendamento excluído')}});

function xmlEsc(s){return String(s??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;')}
function sheetXml(name,headers,rows){return `<Worksheet ss:Name="${xmlEsc(name)}"><Table><Row>${headers.map(h=>`<Cell><Data ss:Type="String">${xmlEsc(h)}</Data></Cell>`).join('')}</Row>${rows.map(r=>`<Row>${r.map(v=>`<Cell><Data ss:Type="${typeof v==='number'?'Number':'String'}">${xmlEsc(v)}</Data></Cell>`).join('')}</Row>`).join('')}</Table></Worksheet>`}
function exportExcel(){const annual=[];for(let m=0;m<12;m++){const d=new Date(selectedYear,m,1),x=calcMonth(d);annual.push([monthLabel(d),x.income,x.expense,x.balance,x.savingRate])}const sheets=[sheetXml('Lançamentos',['Data','Tipo','Categoria','Descrição','Valor','Origem'],txCache.map(t=>[t.date,t.type,t.category,t.description||'',Number(t.amount||0),t.sourceType||'manual'])),sheetXml('Patrimônio',['Tipo','Nome','Valor'],positionsCache.map(p=>[p.type,p.name,Number(p.value||0)])),sheetXml('Recorrentes',['Nome','Tipo','Categoria','Valor','Dia','Início','Fim','Ativa'],recurringCache.map(r=>[r.name,r.type,r.category,Number(r.amount||0),r.dayOfMonth,r.startDate,r.endDate||'',r.active?'Sim':'Não'])),sheetXml('Agendadas',['Nome','Tipo','Categoria','Valor','Vencimento','Frequência','Status'],scheduledCache.map(s=>[s.name,s.type,s.category,Number(s.amount||0),s.dueDate,s.frequency,s.status])),sheetXml(`Ano ${selectedYear}`,['Mês','Receitas','Despesas','Resultado','Taxa de poupança'],annual)];const xml=`<?xml version="1.0"?><Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet" xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet">${sheets.join('')}</Workbook>`;const blob=new Blob([xml],{type:'application/vnd.ms-excel;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`meu-patrimonio-${ymd(new Date())}.xls`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);toast('Arquivo Excel gerado')}
$('#exportExcelBtn').addEventListener('click',exportExcel);$('#exportExcelAnnualBtn').addEventListener('click',exportExcel);

onAuthStateChanged(auth,async u=>{user=u;if(u){$('#authView').classList.add('hidden');$('#appView').classList.remove('hidden');try{await loadAll()}catch(e){console.error(e);toast('Falha ao carregar os dados')}}else{$('#authView').classList.remove('hidden');$('#appView').classList.add('hidden')}});
if('serviceWorker' in navigator)navigator.serviceWorker.register('./sw.js').catch(console.warn);